# Generated by Django 4.2.6 on 2023-10-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='slub',
            new_name='slug',
        ),
    ]
